site_name: 时间序列分析中文网
site_url: https://www.heapoverflow.cn/timeseries/
site_description: 时间序列预测，时间序列异常检测

repo_url: https://github.com/thetechstack/timeseries
edit_uri: edit/main/docs

theme:
  name: material
  font:
    text: Ubuntu
    code: Source Code Pro
  language: zh
  features:
    - navigation.tabs

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - 首页: index.md
  - 基本概念:
      - 平稳性: concepts/stationary.md
